version: "3.8"

services:
  traefik:
    image: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

  mongo:
    image: mongo
    ports:
      # forward port to use during development
      - 27017:27017
    volumes:
      # save data on host filesystem so it is not lost even if we remove container
      - .data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker-workshop
      - MONGO_INITDB_ROOT_PASSWORD=123123

  backend:
    image: docker-workshop-backend
    environment:
      - MONGO_URI=mongodb://docker-workshop:123123@mongo:27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-workshop-backend.rule=Host(`backend.docker-workshop.localhost`) || (Host(`frontend.docker-workshop.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.docker-workshop-backend.middlewares=strip-api"

  frontend:
    image: docker-workshop-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-workshop-frontend.rule=Host(`frontend.docker-workshop.localhost`)"
